# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install modules
      run: npm install
    - name: Build project
      run: npm run build --if-present
    - name: Upload project
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /home/runner/work/Vector-poster-generation-frontend/Vector-poster-generation-frontend/dist
        remote: /etc/nginx/dist
        host: 123.249.36.120
        username: root
        password: Javaee2024
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 123.249.36.120
        username: root
        password: Javaee2024
        port: 22
        script: nginx -s reload
          
    
  
